### ISSUE TITLE
Trial

### ISSUE THREAD

**Issue by annamariakv** [Sneha-K-K/Probability-and-Statistics-with-R-Assignments#1]
Trial

**Comment by Sneha-K-K** [comment]
vada en macchi vazhakkai bajji

**Comment by Sarvesh-77** [comment]
What in the fuck are we doing in this question someone fucking explain me

**Comment by Sneha-K-K** [comment]
lorry ke hote hein tyre, tere muh mein daalun mera myre

**Comment by Sarvesh-77** [comment]
Gandu humara project ki gaand maar raha hai lawde

**Comment by Sarvesh-77** [comment]
> vada en macchi vazhakkai bajji

Idanda myre poi tolle

**Comment by annamariakv** [comment]
This issue was opened as a trial to explore the possibilities.
