### ISSUE TITLE
Question_2 (Sarvesh)

### ISSUE THREAD

**Issue by Sarvesh-77** [Sneha-K-K/Probability-and-Statistics-with-R-Assignments#2]
In this question, we sample n points from a gamma distribution and try to estimate its parameter values using MLE. We vary the sample size (n) and observe the behaviour of our estimate value distribution for 1000 attempts.

**Comment by Sneha-K-K** [comment]
Why are we using geom_vline?

**Comment by annamariakv** [comment]
Why is the gap between 2.5 and 97.5 percentile points decreasing as the sample size increases?

**Comment by Sarvesh-77** [comment]
> Why is the gap between 2.5 and 97.5 percentile points decreasing as the sample size increases?

Google it

**Comment by Sarvesh-77** [comment]
> Why are we using geom_vline?

abline is used for making a general line of the form y = ax + b, but we are interested in making a vertical line to denote the true value of theta on the histogram. Hence, we use geom_vline and create a vertical line.

**Comment by Sneha-K-K** [comment]
The decrease in variance is not visible clearly from the graphs. Maybe we can adjust the xlimits.

**Comment by Sarvesh-77** [comment]
That is a good idea, I will do that.
