### ISSUE TITLE
Question 1 (Anna Maria)

### ISSUE THREAD

**Issue by annamariakv** [Sneha-K-K/Probability-and-Statistics-with-R-Assignments#3]
Question 1

**Comment by Sneha-K-K** [comment]
The stated values for mean and variance are 1.5 and 2.25. But the mean and variance of poisson distribution must be same. How is this possible?

**Comment by annamariakv** [comment]
> The stated values for mean and variance are 1.5 and 2.25. But the mean and variance of poisson distribution must be same. How is this possible?
That's true.

**Comment by Sarvesh-77** [comment]
We can use one of the central tendencies and build our models based on the obtained parameter values, and use it to calculate the other tendencies and compare them with the observed values. Hence we will be able to compare the models and decide upon the best fit.

**Comment by annamariakv** [comment]
That is a good suggestion. I think using the observed mean value to build the models would be a good choice.
