### ISSUE TITLE
Question 4 (Sneha KK)

### ISSUE THREAD

**Issue by Sneha-K-K** [Sneha-K-K/Probability-and-Statistics-with-R-Assignments#5]
Question 4 (Sneha KK)

**Comment by Sneha-K-K** [comment]
I have added my code for question 4. I am getting a good regression line when I assume the underlying distribution is Normal/Laplace. Unfortunately I am getting errors when I try to fit lognormal distribution. Can someone please check this?

**Comment by Sarvesh-77** [comment]
The log normal distribution works with log(x) values, hence we should get rid of the data points where x=0. That could quite possibly be the reason why this error is occurring. Just try deleting the rows from the 'Claims' column in the data, it might work.

**Comment by Sneha-K-K** [comment]
I removed the row and the code is working now. Thank you for the suggestion.

**Comment by Sarvesh-77** [comment]
How did you choose the initial parameters for optim?

**Comment by Sneha-K-K** [comment]
I chose 0 as the starting value for intercept as I felt that the regression line might pass through the origin, and as x goes from 0 to 1000, y varies over 0 and 100, so I felt slope = 0.1 would be a good starting value, and similarly calculated the variance roughly from the graph

**Comment by Sarvesh-77** [comment]
Good that seems correct.
